# fly.toml app configuration file generated for try-pods on 2023-05-08T12:51:54-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "try-pods"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/client/public"
  url_prefix = "/"
