# fly.toml app configuration file generated for try-pods-fly on 2023-05-10T15:41:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "try-pods-fly"
primary_region = "sea"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/client/build"
  url_prefix = "/"
